# Generated by Django 5.1.6 on 2025-04-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='calories',
            field=models.IntegerField(help_text='Calories pour une portion', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='carbs',
            field=models.DecimalField(decimal_places=2, help_text='Glucides pour une portion', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='fat',
            field=models.DecimalField(decimal_places=2, help_text='Lipides pour une portion', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='gluten_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='protein',
            field=models.DecimalField(decimal_places=2, help_text='Protéines pour une portion', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='calories',
            field=models.IntegerField(help_text='Calories pour 100g', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='carbs',
            field=models.DecimalField(decimal_places=2, help_text='Glucides pour 100g', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fat',
            field=models.DecimalField(decimal_places=2, help_text='Lipides pour 100g', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gluten_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='protein',
            field=models.DecimalField(decimal_places=2, help_text='Protéines pour 100g', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
