# Generated by Django 5.1.6 on 2025-04-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_article_calories_article_carbs_article_fat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text="Image de l'article", null=True, upload_to='articles/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Image du produit', null=True, upload_to='products/'),
        ),
    ]
